## â–‘â–ˆâ–€â–€â–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–ˆâ–€â–€â–‘â–ˆâ–‘â–ˆâ–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆ
## â–‘â–€â–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–€â–€â–ˆâ–‘â–ˆâ–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–€
## â–‘â–€â–€â–€â–‘â–‘â–€â–‘â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–‘
##
## based on config from: https://github.com/1amSimp1e/dots/

format="""
$directory\
([î‚¶](bg:#131313 fg:#131313)$git_branch$git_status[î‚´](bg:none fg:#131313) )\
$all"""
add_newline = true

[fill]
symbol = ''

# Other languages configurations:
haskell.disabled = true
ruby.disabled = true
perl.disabled = true

[conda]
format = '[î‚¶]($style)[$symbol$environment](bg:#131313 fg:green)[î‚´]($style)'
style = "bg:none fg:#131313"

# Prompt symbols
[character]
success_symbol = "[-](green bold)"
error_symbol = "[-_-](red bold)"

[directory]
format = "[î—¿ $path](bg:#131313 fg:blue )[î‚´]($style) "
style = "bg:none fg:#131313"
truncation_length = 2

[git_branch]
format = "[$symbol$branch(:$remote_branch)](bg:#131313 fg:purple )"
style = "bg:#131313 fg:purple "

[git_status]
format = "([ $all_status$ahead_behind]($style))"
style = "bg:#131313 fg:cyan"
# conflicted = "="
ahead =	"${count}â‡¡"
behind = "${count}â‡£"
diverged = "${ahead_count}â‡¡${behind_count}â‡£"
untracked = "${count}?"
stashed = "ï†‡ "
modified = "${count}!"
staged = "${count}+"

[python]
format='via [î‚¶]($style)[$symbol$pyenv_prefix($version)( \($virtualenv\))](bg:#131313 fg:yellow bold)[î‚´]($style) '
style = "bg:none fg:#131313"

[nodejs]
format='via [î‚¶]($style)[$symbol($version)](bg:#131313 fg:green )[î‚´]($style) '
style = "bg:none fg:#131313"

[lua]
format='via [î‚¶]($style)[$symbol($version)](bg:#131313 fg:#E8E7E4 )[î‚´]($style) '
style = "bg:none fg:#131313"

[cmd_duration]
min_time = 400
format = "[î‚¶]($style)[$duration](bg:#131313 fg:#E8E7E4 )[î‚´ ]($style)"
style = "bg:none fg:#131313"

[sudo]
disabled = true 
symbol = 'ğŸ‘©â€ğŸ’» '
